In [14]:
import pandas as pd

CAP = 15
# CAP DATA AT 20 OR 15.



def word_count(string):
    return len(string.split(" "))

for i in ['train','valid']:
    for j in ['flickr','mscoco','visualgenome']:
        f = '/data/manifest/{}/{}_manifest.csv'.format(j,i)
        print(f)
        df = pd.read_csv(f)
        df['wordcount'] = df.caption.apply(word_count)
        print('max val', df.wordcount.max())
        print(df[df.wordcount==df.wordcount.max()]['caption'].values)
        
        cramp_df = df[df.wordcount<=CAP]
        print('{} out of {} is 30 len or below. thats {} percent'.format(len(cramp_df),len(df),len(cramp_df)/len(df)))
        print('=========\n')



/data/manifest/flickr/train_manifest.csv
max val 78
['Four young adults sit outside on a wooden deck near a building around a small round table , while another person stands on the edge of the deck , leaning on the wooden railing , with the sun shining on one of them and the rest of them are in the shade , two of them crossing their legs , one holding a cellphone out in front of himself and another holding a green and red soda can.']
99158 out of 127130 is 30 len or below. thats 0.7799732557224888 percent

/data/manifest/mscoco/train_manifest.csv
max val 179
['The intricacies of the motorcycle are                                                                                                                                                                      brought to life  by the sepia photography.']
399981 out of 414113 is 30 len or below. thats 0.9658740488707188 percent

/data/manifest/visualgenome/train_manifest.csv
max val 95
['Two                                               

Retrying (Retry(total=237, connect=237, read=240, redirect=240, status=240)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f032ee0cb80>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /v2.13/tasks.get_all
Retrying (Retry(total=236, connect=236, read=240, redirect=240, status=240)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f032ef48850>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /v2.13/tasks.get_all
Retrying (Retry(total=235, connect=235, read=240, redirect=240, status=240)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f032ef484c0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /v2.13/tasks.get_all


In [18]:
import torch

a = torch.arange(8).reshape((2,2,2)).float()

b = torch.nn.functional.normalize(a,p=2,dim=-1)
print(b)

c = []
for i in range((a.shape[1])):
    d = torch.nn.functional.normalize(a[:,i:i+1,:],p=2,dim=-1)
    c.append(d)
    
c = torch.cat(c,dim=1)
c==b
    


tensor([[[0.0000, 1.0000],
         [0.5547, 0.8321]],

        [[0.6247, 0.7809],
         [0.6508, 0.7593]]])


tensor([[[True, True],
         [True, True]],

        [[True, True],
         [True, True]]])

In [24]:
import torch
learning_rate = 2
model = torch.nn.Linear(2, 1)
def get_learning_rate(epoch):
    if epoch < 10:
        return 1
    elif epoch < 15:
        return 0.5
    else:
        return 0.25
    
optimizer = torch.optim.Adam(
                model.parameters(), lr=learning_rate)
            
    
scheduler = torch.optim.lr_scheduler.LambdaLR(
                optimizer, lr_lambda=get_learning_rate)



lrs = []

for i in range(20):
    optimizer.step()
    lrs.append(optimizer.param_groups[0]["lr"])
#     print("Factor = ", round(0.65 ** i,3)," , Learning Rate = ",round(optimizer.param_groups[0]["lr"],3))
    scheduler.step()
    
print(lrs)

[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1.0, 1.0, 1.0, 1.0, 1.0, 0.5, 0.5, 0.5, 0.5, 0.5]


In [19]:
import dask.dataframe as dd
import os
root_folder = '/data/image_manifest/flickr/train'
data = dd.read_parquet(os.path.join(root_folder),
                                    
                                    )  # this is lazy loading, its not actually loading into memory

In [23]:
from data.text_tensor.dataset import VGTextDataset
from config.config import cfg
train_dataset = VGTextDataset('train', cfg)

/data/parquet/flickr/train


In [25]:
train_dataset[0]

(tensor([[259,  85, 120, 112, 260, 261, 261, 261, 261, 261, 261, 261, 261, 261,
          261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261,
          261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261,
          261, 261, 261, 261, 261, 261, 261, 261],
         [259, 122, 112, 118, 111, 104, 260, 261, 261, 261, 261, 261, 261, 261,
          261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261,
          261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261,
          261, 261, 261, 261, 261, 261, 261, 261],
         [259, 104, 118, 122, 116, 260, 261, 261, 261, 261, 261, 261, 261, 261,
          261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261,
          261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261,
          261, 261, 261, 261, 261, 261, 261, 261],
         [259, 120, 106, 117, 105, 260, 261, 261, 261, 261, 261, 261, 261, 261,
          261, 261, 261, 261, 261, 261, 261, 26

array(['Four young adults sit outside on a wooden deck near a building around a small round table , while another person stands on the edge of the deck , leaning on the wooden railing , with the sun shining on one of them and the rest of them are in the shade , two of them crossing their legs , one holding a cellphone out in front of himself and another holding a green and red soda can.'],
      dtype=object)

In [3]:

import os
from pathlib import Path
from clearml import Dataset, Task

DATA_PROJECT_NAME = "datasets/multimodal"


TASK_NAME = "visual_grounding_training_data_generation"

DATASET_ROOT = '/data/processed/'

OUTPUT_URL = "s3://experiment-logging/multimodal"


input_train_dataset_paths = []
input_valid_dataset_paths = []

args = {

    'num_captions': 5,
    'npartitions': 100,
    'batch_size': 4,
    'input_manifests': ['71a397b04b5d476bb5543306269e28af', ],
    'dataset_name': "VisualGround_FLICKR_manifest_100paritions_4_batch"
}


TEMP_PATH = '/tmp'
if not os.path.exists(TEMP_PATH):
    os.makedirs(TEMP_PATH)
for dataset_id in args['input_manifests']:
    dataset = Dataset.get(dataset_id=dataset_id)
    local_root_path = dataset.get_mutable_local_copy(
        os.path.join(TEMP_PATH, dataset_id))

    input_train_dataset_paths.append(os.path.join(
        local_root_path, 'train_manifest.csv'))

    valid_path = os.path.join(
        local_root_path, 'valid_manifest.csv')

    if os.path.exists(valid_path):
        input_valid_dataset_paths.append(valid_path)
print(input_train_dataset_paths)


2022-04-05 14:06:16,732 - clearml.storage - INFO - Downloading: 5.00MB / 11.55MB @ 11.51MBs from s3://experiment-logging/multimodal/datasets%2Fmultimodal/mscoco_manifest.71a397b04b5d476bb5543306269e28af/artifacts/data/dataset.71a397b04b5d476bb5543306269e28af.zip
2022-04-05 14:06:17,048 - clearml.storage - INFO - Downloading: 10.05MB / 11.55MB @ 15.93MBs from s3://experiment-logging/multimodal/datasets%2Fmultimodal/mscoco_manifest.71a397b04b5d476bb5543306269e28af/artifacts/data/dataset.71a397b04b5d476bb5543306269e28af.zip
2022-04-05 14:06:17,139 - clearml.storage - INFO - Downloaded 11.55 MB successfully from s3://experiment-logging/multimodal/datasets%2Fmultimodal/mscoco_manifest.71a397b04b5d476bb5543306269e28af/artifacts/data/dataset.71a397b04b5d476bb5543306269e28af.zip , saved to /root/.clearml/cache/storage_manager/datasets/8da9728d393f1f5a5076e2defd9b9e36.dataset.71a397b04b5d476bb5543306269e28af.zip
['/tmp/71a397b04b5d476bb5543306269e28af/train_manifest.csv']
